### ISSUE TITLE
Use MicroKernel instead of Kernel for the next release

### ISSUE THREAD

**Issue by mickaelandrieu** [gnugat/symfony-empty-edition#2]
More informations here => http://symfony.com/blog/new-in-symfony-2-8-symfony-as-a-microframework

What do you think @gnugat ?

**Comment by gnugat** [comment]
![Nope](http://ohtoptens.com/wp-content/uploads/2015/05/Grumpy-Cat-NO-1.jpg)

**Comment by gnugat** [comment]
More seriously that might be a good idea for a "micro framework" edition, but not for the empty edition as its purpose is to allow you to make the decisions without hinting to a direction.

**Comment by mickaelandrieu** [comment]
ok ok :) thank for the answer !

**Comment by gnugat** [comment]
;)
