### ISSUE TITLE
Some components are missing

### ISSUE THREAD

**Issue by jakzal** [gnugat/symfony-empty-edition#3]
`app/console` exists in the repository, but `symfony/console` is not being installed after running `composer install`. Nor is `symfony/finder` (required by the Bundle class) or `symfony/process` (required by the server:run command). Possibly more.

**Comment by gnugat** [comment]
Thanks for the feedback, so far I've spotted another missing dependency: `symfony/yaml`. I'll fix that shortly.

**Comment by gnugat** [comment]
I've updated the edition to Symfony 3 and the new directory structure, and I took the opportunity to add `symofny/console`, `symofny/finder` and `symfony/yaml`.
I've then created a new route and given it a try and all went well. I guess all those extra dependencies are actually optional (e.g. if you want to use the `server:run` command you need to install `symfony/process`).

**Comment by jakzal** [comment]
Since https://github.com/symfony/symfony/pull/16871 was merged, I agree that the process component can be treated as optional (since the commands would be simply hidden).
