### ISSUE TITLE
Mark repository as abandoned

### ISSUE THREAD

**Issue by garak** [gnugat/symfony-empty-edition#7]
I guess this project makes no sense anymore. Now you can achieve the same (or better) result using symfony/flex.
You should deprecate this, marking package as abandoned on packagist and putting repo in read only mode.

**Comment by gnugat** [comment]
Hello @garak,

I believe the Empty Edition can still coexist with Symfony Flex, so I definitely won't abandon/deprecate it. I should probably update it for Symfony 4 though, thanks for the reminder!
